#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/cudy-forward-monitor
    procd_set_param respawn 30 5 5
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param env LOG=/tmp/cudy-forward-monitor.log
    procd_set_param env INTERVAL=5
    procd_set_param env MAX_LINES=3000
    procd_close_instance
}
