#!/usr/bin/env python3
"""Regression checks for Linux agent install/packaging scripts."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AGENT_DIR = ROOT / "tools" / "agent-linux"
BUILD_SCRIPT = ROOT / "tools" / "Build-LinuxAgentPackage.ps1"
UPDATE_BUILD_SCRIPT = ROOT / "tools" / "Build-AgentUpdateArtifacts.ps1"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def assert_contains(text: str, needle: str, *, label: str) -> None:
    if needle not in text:
        raise AssertionError(f"{label} missing expected snippet: {needle}")


def assert_not_contains(text: str, needle: str, *, label: str) -> None:
    if needle in text:
        raise AssertionError(f"{label} still contains forbidden snippet: {needle}")


def main() -> int:
    restore = read_text(AGENT_DIR / "restore_direct.sh")
    one_click = read_text(AGENT_DIR / "one_click_install.sh")
    agent_on = read_text(AGENT_DIR / "agent_on.sh")
    agent_off = read_text(AGENT_DIR / "agent_off.sh")
    agent_ui = read_text(AGENT_DIR / "cudy_agent_ui.sh")
    agent_ui_py = read_text(AGENT_DIR / "cudy_agent_ui.py")
    open_user_ui = read_text(AGENT_DIR / "open_user_ui.sh")
    diagnostics = read_text(AGENT_DIR / "run_diagnostics.sh")
    speed_tests = read_text(AGENT_DIR / "run_speed_tests.sh")
    shortcuts = read_text(AGENT_DIR / "install_desktop_shortcuts.sh")
    fresh_install = read_text(AGENT_DIR / "fresh_install_from_zip.sh")
    self_install_readme = read_text(AGENT_DIR / "SELF-INSTALL-README-RU.txt")
    installer = read_text(AGENT_DIR / "install_singbox_runtime.sh")
    managed = read_text(AGENT_DIR / "managed_agent.sh")
    start_tunnel = read_text(AGENT_DIR / "start_tunnel.sh")
    status = read_text(AGENT_DIR / "status.sh")
    updater = read_text(AGENT_DIR / "update_agent.sh")
    watchdog = read_text(AGENT_DIR / "watch_agent_connectivity.py")
    install_systemd = read_text(AGENT_DIR / "install_systemd.sh")
    uninstall_systemd = read_text(AGENT_DIR / "uninstall_systemd.sh")
    builder = read_text(BUILD_SCRIPT)
    update_builder = read_text(UPDATE_BUILD_SCRIPT)

    assert_contains(
        restore,
        'dns_value="${RESTORE_DNS_SERVERS:-${gw:-192.168.1.1} 1.1.1.1}"',
        label="restore_direct.sh",
    )
    assert_contains(restore, 'read -r -a dns_servers <<< "$dns_value"', label="restore_direct.sh")
    assert_contains(restore, 'resolvectl dns "$dev" "${dns_servers[@]}"', label="restore_direct.sh")
    assert_contains(restore, 'resolvectl default-route "$dev" yes', label="restore_direct.sh")
    assert_contains(restore, "--keep-transports", label="restore_direct.sh")
    assert_contains(restore, 'resolvectl revert "$link_name"', label="restore_direct.sh")
    assert_contains(restore, "cleanup_half_route()", label="restore_direct.sh")
    assert_contains(restore, "RESTORE_FORCE_HALF_ROUTES", label="restore_direct.sh")
    assert_contains(restore, 'ip route del "$prefix"', label="restore_direct.sh")
    assert_not_contains(
        restore,
        'resolvectl dns "$dev" "${RESTORE_DNS_SERVERS:-192.168.1.254 1.1.1.1}"',
        label="restore_direct.sh",
    )

    assert_contains(one_click, 'socket.getaddrinfo("api.github.com", 443)', label="one_click_install.sh")
    assert_contains(one_click, "DNS cannot resolve api.github.com", label="one_click_install.sh")
    assert_contains(one_click, "chmod +x ./runtime/sing-box", label="one_click_install.sh")
    assert_contains(one_click, "--strict-smoke", label="one_click_install.sh")
    assert_contains(one_click, "--smoke", label="one_click_install.sh")
    assert_contains(one_click, "--start", label="one_click_install.sh")
    assert_contains(one_click, "one-shot managed agent smoke failed", label="one_click_install.sh")
    assert_contains(one_click, "keep agent OFF", label="one_click_install.sh")
    assert_contains(one_click, "will remain OFF", label="one_click_install.sh")
    assert_contains(one_click, "./agent_off.sh", label="one_click_install.sh")
    assert_contains(one_click, "install_desktop_shortcuts.sh", label="one_click_install.sh")
    assert_contains(one_click, 'sudo -u "$SUDO_USER"', label="one_click_install.sh")
    assert_contains(agent_on, "systemctl restart", label="agent_on.sh")
    assert_contains(agent_on, "rerun_as_root()", label="agent_on.sh")
    assert_contains(agent_on, '[ -n "${DISPLAY:-}" ]', label="agent_on.sh")
    assert_contains(agent_on, "pkexec /bin/bash", label="agent_on.sh")
    assert_contains(agent_on, "no terminal or pkexec prompt is available", label="agent_on.sh")
    assert_contains(agent_on, "Cudy agent is ON.", label="agent_on.sh")
    assert_contains(agent_off, "systemctl disable --now", label="agent_off.sh")
    assert_contains(agent_off, "rerun_as_root()", label="agent_off.sh")
    assert_contains(agent_off, '[ -n "${DISPLAY:-}" ]', label="agent_off.sh")
    assert_contains(agent_off, "pkexec /bin/bash", label="agent_off.sh")
    assert_contains(agent_off, "no terminal or pkexec prompt is available", label="agent_off.sh")
    assert_contains(agent_off, "systemctl reset-failed", label="agent_off.sh")
    assert_contains(agent_off, "./restore_direct.sh", label="agent_off.sh")
    assert_contains(agent_off, "Cudy agent is OFF.", label="agent_off.sh")
    assert_contains(shortcuts, "Cudy Agent", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "cudy_agent_ui.sh", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "Cudy Agent ON", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "Cudy Agent OFF", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "Cudy Agent Status", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "metadata::trusted", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "Terminal=$terminal", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "cudy-agent.desktop", label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, '"false"', label="install_desktop_shortcuts.sh")
    assert_contains(shortcuts, "Press Enter to close", label="install_desktop_shortcuts.sh")
    assert_contains(agent_ui, "zenity", label="cudy_agent_ui.sh")
    assert_contains(agent_ui, "terminal_menu", label="cudy_agent_ui.sh")
    assert_contains(agent_ui, "exec python3 ./cudy_agent_ui.py", label="cudy_agent_ui.sh")
    assert_contains(agent_ui, "./open_user_ui.sh", label="cudy_agent_ui.sh")
    assert_contains(agent_ui, "./run_diagnostics.sh", label="cudy_agent_ui.sh")
    assert_contains(agent_ui_py, 'self.root.geometry("900x700")', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'self.root.minsize(820, 620)', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Canvas", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "draw_indicator", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'Tk(className="CudyAgent")', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "build_status_icons", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "self.root.iconphoto(True, status_icon)", label="cudy_agent_ui.py")
    assert_contains(shortcuts, "StartupWMClass=CudyAgent", label="install_desktop_shortcuts.sh")
    assert_contains(agent_ui_py, "CONTROL_START_GRACE_SECONDS", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "watchdog_recovery_pending", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'title = "RECOVERY"', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Direct internet restored; retrying agent soon", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'title = "UPDATING"', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "internet may be briefly unavailable", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "UPDATE_MARKER_FILE", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "restart_window_after_background_update", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'state="disabled" if info["updating"] else "normal"', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'title = "STARTING"', label="cudy_agent_ui.py")
    if 'title = "START"' in agent_ui_py:
        raise AssertionError("Linux UI must label the transient state as STARTING, not START")
    assert_contains(agent_ui_py, "service_active_age_seconds", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "ActiveEnterTimestampMonotonic", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Connecting...", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "read_managed_traffic_counters", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "self.traffic_delta +=", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Routing rules: {revision}, synchronized", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Software update: downloading", label="cudy_agent_ui.py")
    assert_not_contains(agent_ui_py, '("checking", "downloading"', label="cudy_agent_ui.py")
    if 'f"Version: current {current_name or \'-\'} ({current_code})' in agent_ui_py:
        raise AssertionError("Linux UI must not expose internal version codes")
    assert_contains(agent_ui_py, "format_mb", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "this session", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "width=24, height=12", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'self.listbox.bind("<Double-Button-1>"', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "subprocess.TimeoutExpired", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "approve it and retry", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '("ON", ["./agent_on.sh"], 180)', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '("OFF + Exit", ["./agent_off.sh"], 180)', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '("Exit UI", self.exit_ui_command, 5)', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'if label == "OFF + Exit" and rc == 0:', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "self.speed_url", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "self.version_status", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "latest_version()", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "/api/agent/app-version?platform=", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "self.update_button", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "run_update", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '["./update_agent.sh"]', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "UPDATE_ACTION_LABELS", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "launch_fresh_ui", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "update_started", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "wait_for_update_and_restart", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Restarting Cudy Agent window", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Waiting for updated files", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "AGENT_UPDATE_STATUS_FILE", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "read_update_status()", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Updating agent; internet may be briefly unavailable", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Installing the approved update. Some services may be briefly unavailable.", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Custom URL (optional)", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Fast Speed", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '["./run_speed_tests.sh", "--quick"]', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Full Speed", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "URL Test", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "speed_test_command", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '["./run_speed_tests.sh", "--only-url", url]', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Update / Repair", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "force_update_command", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, '["./update_agent.sh", "--force"]', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Double-click an action on the left.", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Window close exits UI only. Turn OFF stops the service.", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Copy Result", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Close Window", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "copy_output", label="cudy_agent_ui.py")
    assert_contains(open_user_ui, "/agent-login?token=", label="open_user_ui.sh")
    assert_contains(open_user_ui, "wait_for_managed_control_tunnel()", label="open_user_ui.sh")
    assert_not_contains(open_user_ui, "./start_tunnel.sh", label="open_user_ui.sh")
    assert_contains(diagnostics, "/api/agent/diagnostics", label="run_diagnostics.sh")
    assert_contains(diagnostics, "wait_for_control_tunnel()", label="run_diagnostics.sh")
    assert_not_contains(diagnostics, "./start_tunnel.sh", label="run_diagnostics.sh")
    assert_contains(diagnostics, "mail -s", label="run_diagnostics.sh")
    assert_contains(diagnostics, "sendmail -t", label="run_diagnostics.sh")
    assert_contains(diagnostics, "xdg-email", label="run_diagnostics.sh")
    assert_contains(diagnostics, "isasha@list.ru", label="run_diagnostics.sh")
    assert_contains(diagnostics, "journalctl", label="run_diagnostics.sh")
    assert_contains(diagnostics, "copy_report_to_clipboard()", label="run_diagnostics.sh")
    assert_contains(diagnostics, "wl-copy", label="run_diagnostics.sh")
    assert_contains(diagnostics, "xclip -selection clipboard", label="run_diagnostics.sh")
    assert_contains(diagnostics, "xsel --clipboard --input", label="run_diagnostics.sh")
    assert_contains(diagnostics, "Diagnostic report copied to clipboard.", label="run_diagnostics.sh")
    assert_contains(speed_tests, "--only-url", label="run_speed_tests.sh")
    assert_contains(speed_tests, "--quick", label="run_speed_tests.sh")
    assert_contains(speed_tests, "baseline_direct_yandex_mirror_reference", label="run_speed_tests.sh")
    assert_contains(speed_tests, "reference_direct_yandex_mirror_download", label="run_speed_tests.sh")
    assert_contains(speed_tests, "reference_cloudflare_cdn_25mb", label="run_speed_tests.sh")
    assert_contains(speed_tests, "What this measures:", label="run_speed_tests.sh")
    assert_contains(speed_tests, "readable result table", label="run_speed_tests.sh")
    assert_contains(speed_tests, "CUSTOM_URLS", label="run_speed_tests.sh")
    assert_contains(speed_tests, "speed_Mbps", label="run_speed_tests.sh")
    assert_contains(speed_tests, "route_to_host", label="run_speed_tests.sh")
    assert_contains(speed_tests, "/api/agent/diagnostics", label="run_speed_tests.sh")
    assert_contains(speed_tests, "Speed test report sent to control-server.", label="run_speed_tests.sh")
    assert_contains(fresh_install, 'find "$work_dir" -mindepth 1 -maxdepth 1 -type d', label="fresh_install_from_zip.sh")
    assert_contains(fresh_install, "sudo rm -rf --one-file-system", label="fresh_install_from_zip.sh")
    assert_contains(fresh_install, "sudo systemctl reset-failed cudy-managed-agent.service", label="fresh_install_from_zip.sh")
    assert_contains(fresh_install, "sudo ./one_click_install.sh", label="fresh_install_from_zip.sh")
    assert_contains(fresh_install, "./test_prod_agent.sh", label="fresh_install_from_zip.sh")
    assert_contains(self_install_readme, "bash ./install.sh", label="SELF-INSTALL-README-RU.txt")
    assert_contains(installer, "from urllib.error import URLError", label="install_singbox_runtime.sh")
    assert_contains(installer, "cannot query GitHub release API", label="install_singbox_runtime.sh")
    assert_contains(start_tunnel, "-o BatchMode=yes", label="start_tunnel.sh")
    assert_contains(start_tunnel, "-o IdentitiesOnly=yes", label="start_tunnel.sh")
    assert_contains(start_tunnel, "STRICT_HOST_KEY_CHECKING=accept-new", label="start_tunnel.sh")
    assert_contains(start_tunnel, "STRICT_HOST_KEY_CHECKING=yes", label="start_tunnel.sh")
    assert_contains(
        start_tunnel,
        '-o StrictHostKeyChecking="$STRICT_HOST_KEY_CHECKING"',
        label="start_tunnel.sh",
    )
    assert_contains(start_tunnel, "CONTROL_CONNECT_TIMEOUT", label="start_tunnel.sh")
    assert_contains(start_tunnel, "CONTROL_HOST_KEY_SHA256", label="start_tunnel.sh")
    assert_contains(start_tunnel, "prepare_known_host", label="start_tunnel.sh")
    assert_contains(start_tunnel, "control-server SSH key mismatch", label="start_tunnel.sh")
    assert_contains(managed, "CONTROL_TUNNEL_WAIT_SECONDS", label="managed_agent.sh")
    assert_contains(managed, "cache_authenticated_control_endpoint", label="managed_agent.sh")
    assert_contains(managed, "run/control-endpoint.env", label="managed_agent.sh")
    assert_contains(managed, "stop_control_tunnel()", label="managed_agent.sh")
    assert_contains(managed, "cleanup_orphaned_control_tunnels()", label="managed_agent.sh")
    assert_contains(managed, '"${CONTROL_USER}@${CONTROL_HOST}"', label="managed_agent.sh")
    assert_contains(managed, "dump_control_tunnel_logs()", label="managed_agent.sh")
    assert_contains(managed, "restore_direct_dns_baseline()", label="managed_agent.sh")
    assert_contains(managed, "./restore_direct.sh --keep-transports", label="managed_agent.sh")
    assert_contains(managed, "AGENT_AUTO_UPDATE", label="managed_agent.sh")
    assert_contains(managed, "AGENT_UPDATE_CHECK_SECONDS", label="managed_agent.sh")
    assert_contains(managed, "schedule_update_check()", label="managed_agent.sh")
    assert_contains(managed, "flock -n 9", label="managed_agent.sh")
    assert_contains(managed, "schedule_update_check\n      cycle_ok=1", label="managed_agent.sh")
    assert_contains(managed, "--can-manage-transports", label="managed_agent.sh")
    assert_contains(managed, "./update_agent.sh --from-agent", label="managed_agent.sh")
    assert_contains(managed, "while true; do\n  mkdir -p run logs transports", label="managed_agent.sh")
    assert_contains(updater, "/api/agent/app-version?platform=", label="update_agent.sh")
    assert_contains(updater, "rerun_as_root_for_manual_update()", label="update_agent.sh")
    assert_contains(updater, "ORIGINAL_ARGS", label="update_agent.sh")
    assert_contains(updater, "FORCE_UPDATE", label="update_agent.sh")
    assert_contains(updater, "--force", label="update_agent.sh")
    assert_contains(updater, "root permissions are required to update the agent", label="update_agent.sh")
    assert_contains(updater, "pkexec /bin/bash", label="update_agent.sh")
    assert_contains(updater, "--apply-staged", label="update_agent.sh")
    assert_contains(updater, "copy_update_files()", label="update_agent.sh")
    assert_contains(updater, "agent.env|uswest_control_tunnel_ed25519", label="update_agent.sh")
    assert_contains(updater, 'if [ -f "$VERSION_FILE" ]; then', label="update_agent.sh")
    assert_contains(updater, 'if [ -n "${AGENT_VERSION_CODE:-}" ]; then', label="update_agent.sh")
    if updater.index('if [ -f "$VERSION_FILE" ]; then') > updater.index('if [ -n "${AGENT_VERSION_CODE:-}" ]; then'):
        raise AssertionError("update_agent.sh must prefer agent.version.json over AGENT_VERSION_CODE")
    assert_contains(updater, "Installed version code: $(current_version_code)", label="update_agent.sh")
    assert_contains(updater, "start_apply_staged_update()", label="update_agent.sh")
    assert_contains(updater, "UPDATE_STATUS_FILE", label="update_agent.sh")
    assert_contains(updater, "UPDATE_MARKER_FILE", label="update_agent.sh")
    assert_contains(updater, "write_update_marker()", label="update_agent.sh")
    assert_contains(updater, "clear_update_marker()", label="update_agent.sh")
    assert_contains(updater, "write_update_status()", label="update_agent.sh")
    assert_contains(updater, "Some services may be temporarily unavailable until update finishes.", label="update_agent.sh")
    assert_contains(updater, "up_to_date current=", label="update_agent.sh")
    assert_contains(updater, "systemd-run", label="update_agent.sh")
    assert_contains(updater, "--working-directory", label="update_agent.sh")
    assert_contains(updater, "Cudy Agent self-update", label="update_agent.sh")
    assert_contains(updater, "setsid", label="update_agent.sh")
    assert_contains(updater, "exit 10", label="update_agent.sh")
    assert_contains(watchdog, 'CONFIG_PATH = RUN_DIR / "fresh-config.json"', label="watch_agent_connectivity.py")
    assert_contains(watchdog, 'managed.get("critical_services")', label="watch_agent_connectivity.py")
    assert_contains(watchdog, "failure_pattern", label="watch_agent_connectivity.py")
    assert_contains(watchdog, "Base connectivity failure threshold reached", label="watch_agent_connectivity.py")
    assert_contains(watchdog, 'subprocess.run(["systemctl", "stop", service_name]', label="watch_agent_connectivity.py")
    assert_not_contains(watchdog, 'subprocess.run(["systemctl", "disable", "--now", service_name]', label="watch_agent_connectivity.py")
    assert_contains(watchdog, '"critical_service_failed"', label="watch_agent_connectivity.py")
    assert_contains(watchdog, '"direct_recovery_cooldown"', label="watch_agent_connectivity.py")
    assert_contains(watchdog, "reporting without stopping the agent", label="watch_agent_connectivity.py")
    assert_contains(watchdog, 'ROOT / "restore_direct.sh"', label="watch_agent_connectivity.py")
    assert_contains(install_systemd, "watchdog.timer", label="install_systemd.sh")
    assert_contains(install_systemd, "OnUnitActiveSec=30", label="install_systemd.sh")
    assert_contains(install_systemd, "enable --now", label="install_systemd.sh")
    assert_contains(uninstall_systemd, "watchdog_timer", label="uninstall_systemd.sh")
    assert_contains(uninstall_systemd, "stop_singbox_transport.sh", label="uninstall_systemd.sh")
    assert_contains(uninstall_systemd, "systemctl reset-failed", label="uninstall_systemd.sh")
    start_transport = read_text(AGENT_DIR / "start_singbox_transport.sh")
    stop_transport = read_text(AGENT_DIR / "stop_singbox_transport.sh")
    assert_contains(start_transport, "is_managed_transport_pid()", label="start_singbox_transport.sh")
    assert_contains(start_transport, 'ip link show "$name"', label="start_singbox_transport.sh")
    assert_contains(start_transport, "TUN interface is missing", label="start_singbox_transport.sh")
    assert_contains(start_transport, "sanitize_transport_dns()", label="start_singbox_transport.sh")
    assert_contains(start_transport, 'resolvectl revert "$name"', label="start_singbox_transport.sh")
    assert_contains(start_transport, 'resolvectl default-route "$name" no', label="start_singbox_transport.sh")
    assert_contains(stop_transport, 'pgrep -f "sing-box run -c transports/${name}\\\\.json"', label="stop_singbox_transport.sh")
    assert_contains(stop_transport, '[[ "$cmd" == *sing-box*', label="stop_singbox_transport.sh")
    assert_contains(stop_transport, 'resolvectl revert "$name"', label="stop_singbox_transport.sh")
    assert_contains(stop_transport, 'resolvectl default-route "$name" no', label="stop_singbox_transport.sh")
    assert_contains(managed, 'resolvectl revert "$link_name"', label="managed_agent.sh")
    assert_contains(managed, 'resolvectl default-route "$link_name" no', label="managed_agent.sh")
    assert_contains(one_click, "fix_workdir_permissions()", label="one_click_install.sh")
    assert_contains(one_click, "SUDO_UID", label="one_click_install.sh")
    assert_contains(one_click, "stop_all_managed_transports()", label="one_click_install.sh")
    assert_contains(one_click, "needs_direct_restore()", label="one_click_install.sh")
    assert_contains(one_click, "cleanup_direct_half_routes()", label="one_click_install.sh")
    assert_contains(one_click, "install_optional_ui_dependencies()", label="one_click_install.sh")
    assert_contains(one_click, "python_tk_available()", label="one_click_install.sh")
    assert_contains(one_click, "import tkinter", label="one_click_install.sh")
    assert_contains(one_click, "CUDY_SKIP_UI_DEPS", label="one_click_install.sh")
    assert_contains(one_click, "DEBIAN_FRONTEND=noninteractive apt-get install -y python3-tk", label="one_click_install.sh")
    assert_contains(one_click, "desktop UI will fall back to zenity/terminal mode", label="one_click_install.sh")
    assert_contains(one_click, "remove stale direct half-routes only", label="one_click_install.sh")
    assert_contains(one_click, "sudo systemctl reset-failed", label="one_click_install.sh")
    assert_contains(read_text(AGENT_DIR / "test_prod_agent.sh"), "mktemp", label="test_prod_agent.sh")
    assert_contains(read_text(AGENT_DIR / "test_prod_agent.sh"), "control_health()", label="test_prod_agent.sh")
    assert_contains(read_text(AGENT_DIR / "test_prod_agent.sh"), "control health attempt", label="test_prod_agent.sh")
    assert_contains(read_text(AGENT_DIR / "test_prod_agent.sh"), "no managed route in control config", label="test_prod_agent.sh")
    assert_contains(read_text(AGENT_DIR / "test_prod_agent.sh"), ". \"$selection_env\"", label="test_prod_agent.sh")
    assert_contains(status, "control listeners/processes", label="status.sh")
    assert_contains(status, "ss -ltnp", label="status.sh")
    assert_contains(status, 'ps -p "$pid"', label="status.sh")
    assert_contains(status, "systemctl show", label="status.sh")
    assert_not_contains(status, "systemctl --no-pager --full status", label="status.sh")
    assert_contains(status, "ufw status requires root; skipped", label="status.sh")

    for label, script in {
        "managed_agent.sh": managed,
        "start_tunnel.sh": start_tunnel,
        "status.sh": status,
        "agent_on.sh": agent_on,
        "agent_off.sh": agent_off,
        "open_user_ui.sh": open_user_ui,
    }.items():
        assert_contains(script, "strip_cr()", label=label)
        assert_contains(script, "tr -d '\\r'", label=label)

    assert_contains(builder, "Copy-TextFileLf", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "New-ZipFromDirectoryUnix", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "$entryName = $relative -replace '\\\\', '/'", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "-replace \"`r`n\", \"`n\"", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "$AgentId-install.sh", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "$AgentId-self-install.sh", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "$AgentId-self-install.zip", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"install.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "SELF-INSTALL-README-RU.txt", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "__CUDY_AGENT_ZIP_BASE64_BELOW__", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "install agent in OFF state", label="Build-LinuxAgentPackage.ps1")
    assert_not_contains(builder, "production smoke test failed", label="Build-LinuxAgentPackage.ps1")
    assert_not_contains(builder, "installed service will keep retrying", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "sudo ./uninstall_systemd.sh cudy-managed-agent.service", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "sudo systemctl reset-failed cudy-managed-agent.service", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "unzip_rc=$?", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, 'if [ "$unzip_rc" -gt 1 ]; then', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "IncludeRuntime", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "runtime", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "[string]$VersionName", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "[int]$VersionCode", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "version_name = $VersionName", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, "version_code = $VersionCode", label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"agent_on.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"agent_off.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"install_desktop_shortcuts.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"cudy_agent_ui.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"cudy_agent_ui.py"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"open_user_ui.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"run_diagnostics.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"run_speed_tests.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"update_agent.sh"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"watch_agent_connectivity.py"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(builder, '"agent.version.json"', label="Build-LinuxAgentPackage.ps1")
    assert_contains(update_builder, '"watch_agent_connectivity.py"', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(update_builder, '[string[]]$Platforms', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(update_builder, '$selectedPlatforms -contains "android"', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(update_builder, '[string]$LinuxVersionName = "1.31"', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(update_builder, '[int]$LinuxVersionCode = 32', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(update_builder, 'version_name = $LinuxVersionName', label="Build-AgentUpdateArtifacts.ps1")
    assert_contains(updater, "wait_for_service_active", label="update_agent.sh")
    assert_contains(updater, 'systemctl is-active --quiet "$SERVICE_NAME"', label="update_agent.sh")
    assert_contains(updater, "service=active control=ready", label="update_agent.sh")
    assert_contains(updater, 'rm -rf -- "$WORK_DIR"', label="update_agent.sh")
    assert_contains(updater, "ready_to_install current=", label="update_agent.sh")
    assert_contains(updater, "progress=", label="update_agent.sh")
    assert_contains(updater, "The current agent remains active.", label="update_agent.sh")
    assert_contains(updater, "waiting for user approval", label="update_agent.sh")
    assert_contains(updater, 'if [ "$FROM_AGENT" = "1" ]; then', label="update_agent.sh")
    assert_contains(updater, 'actual_sha256="$(sha256sum "$archive"', label="update_agent.sh")
    assert_contains(agent_ui_py, 'text="Install Update" if update_ready else "Update"', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "prompt_staged_update", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "The current version will keep working until you approve installation.", label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, "Software update: downloading in background", label="cudy_agent_ui.py")
    assert_not_contains(
        updater,
        'systemctl restart "$SERVICE_NAME" || true',
        label="update_agent.sh",
    )
    assert_contains(agent_ui_py, 'if "completed current=" in status:', label="cudy_agent_ui.py")
    assert_contains(agent_ui_py, 'if "failed" in status:', label="cudy_agent_ui.py")
    assert_contains(watchdog, "recover_enabled_service", label="watch_agent_connectivity.py")
    assert_contains(watchdog, 'default=60', label="watch_agent_connectivity.py")
    assert_contains(watchdog, '["systemctl", "restart", name]', label="watch_agent_connectivity.py")
    assert_contains(watchdog, '"failed_services": ["agent-service"]', label="watch_agent_connectivity.py")

    print("Linux agent packaging regression passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
